version: '3.8'

services:
  movieapi:
    build:
      context: .
      dockerfile: MovieAPI/Dockerfile
    ports:
      - "8080:80"  # maps http://localhost:8080 
    volumes:
      - ./MovieAPI/Data/movies.db:/app/movies.db  
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
